# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_chegada', models.TimeField()),
                ('objetivos', models.TextField()),
                ('materiais_metodos', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField()),
                ('avaliacao', models.TextField(default='')),
                ('atividades_futuras', models.TextField(blank=True, null=True)),
                ('bibliografia', models.TextField(blank=True, null=True)),
                ('hora_saida', models.TimeField()),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
