# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('objetivos', models.TextField()),
                ('hora_chegada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('resultados', models.TextField()),
            ],
        ),
    ]
