# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='atividades_futuras',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='avaliacao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='diario',
            name='bibliografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diario',
            name='materiais_metodos',
            field=models.TextField(null=True),
        ),
    ]
