# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170208_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='atividades_futuras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='bibliografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='materiais_metodos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
